version: '3.9'

services:
  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9100

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - --docker_only
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8080
