version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
      GF_INSTALL_PLUGINS: grafana-oncall-app
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
