services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: oncall
      POSTGRES_USER: oncall
      POSTGRES_PASSWORD: oncall

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
