version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    restart: always
    user: root
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus_data:
