version: "3.9"

services:
  ubuntu:
    image: ubuntu:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: sh -c "apt update && apt install -y nano vim curl && bash"
